### ISSUE TITLE
How to handle nested focusnodes? 

### ISSUE THREAD

**Issue by ariejan** [pmutisya/keymap#3]
`KeyboardWidget` is a top level widget, handling keyboard shortcuts. I this example I want to bind the `x` key:

```
KeyAction(LogicalKeyboardKey.keyX, 'toggle item complete/uncomplete', () {
    // Implementation not relevant
}),
```

This works fine. 

But when I focus on a `TextField`, the `x` key is not working for text input, but is still being handled by `KeyboardWidget`. 

I know I can add a modifier key to omit this problem, but I'm trying to replicate existing keybindings for ease-of-use. 

How can I circumvent this problem? Is there a change needed in keymap for this? (I'd be happy to supply a patch if so).

**Comment by pmutisya** [comment]
I'm working on that now. Flutter seems to be in the middle of redesigning the focus and keyboard handling system, moving from RawKeyEvents. Please feel free to suggest a patch.

**Comment by pmutisya** [comment]
I have updated widget to only handle key events when it has primary focus. There is now an included an example (textfield_example.dart) that shows this in action
