### ISSUE TITLE
Shortcuts don't work after web hot restart

### ISSUE THREAD

**Issue by sils** [pmutisya/keymap#7]
Using the web platform here and basically the sample code (just playing around).

Whenever I do a hot restart, the shortcuts don't seem to work anymore.

Reloading the app (F5) seems to then fix it again.

**Comment by sils** [comment]
Actually this might actually not be the hot reload, I think it's clicking outside the tab and then back in again.

So steps to reproduce seem to be:

1. Start the app in chrome (web build)
2. Try a shortcut (works)
3. Click outside chrome
4. Click inside chrome
5. Try a shortcut (doesn't work)

**Comment by sils** [comment]
Note: I'm using 0.0.90 (latest from pubdev)

**Comment by sils** [comment]
Update: I ended up switching to CallbackShortcuts and putting it outside my scaffold, I don't know how exactly that changes things but it fixed it for me.

Maybe worth pointing out in the docs and explaining?

**Comment by pmutisya** [comment]
Version 0.0.92 should fix this. Tested successfully.
